pdf: main.tex refs.bib
	latexmk -f -interaction=nonstopmode -pdf main.tex

clean:
	rm -rf *.aux *.bcf *.lof *.log *.out *.run.xml *.toc *.bbl *.blg *.fdb_latexmk *.fls *.nav *.snm *.mtc* *.maf *.pdf

.PHONY: pdf clean
